### ISSUE TITLE
missing shellcheck SCxxx prefix in "message" attribute  

### ISSUE THREAD

**Issue by amurashkin17** [bash-lsp/bash-language-server#865] opened 2023-06-04 20:30 UTC
### Code editor

Eclipse 2023-06, ShellWax 1.2.2.20221209-1429

### Platform

Fedora Linux 38

### Version

4.1.0

### What steps will reproduce the bug?

In Eclipse, install ShellWax plugin. Create a bash script that has some some issues, for example

```
#!/usr/bin/bash
a=2
(( $a == 1 ))
```

Observe that the error message does not have SC2004 prefix

_$/${} is unnecessary on arithmetic variables._

### How often does it reproduce? Is there a required condition?

Always happens. 

### What is the expected behavior?

In bash language server diagnostics, "message" attribute has SCxxx prefix, for example
```
{
    "message":"SC2004: $/${} is unnecessary on arithmetic variables.",
    "severity":4,
    "code":"SC2004",
    "source":"shellcheck",
    "range":{"start":{"line":2,"character":11},"end":{"line":2,"character":17}},
    "codeDescription":{"href":"https://www.shellcheck.net/wiki/SC2004"}
},
```

### What do you see instead?

In bash language server 4.1.0 diagnostics, "message" attribute does not have SCxxx prefix, for example
```
{
    "message":"$/${} is unnecessary on arithmetic variables.",
    "severity":4,
    "code":"SC2004",
    "source":"shellcheck",
    "range":{"start":{"line":2,"character":11},"end":{"line":2,"character":17}},
    "codeDescription":{"href":"https://www.shellcheck.net/wiki/SC2004"}
},
```

### Additional information

Correspondent ShellWax issue is [#92 Missing shellcheck SCxxx code in messages](https://github.com/eclipse/lsp4e/issues/686).

While removing the prefix makes sense as there is "code" attribute, it nevertheless breaks existing bash language clients.

In ShellWax 1.2.2.20221209-1429, bash language server 4.1.0, shellcheck error messages do not include SCxxx code, for example

_read without -r will mangle backslashes_
**echo "$*" | while IFS= read line; do**

In ShellWax 1.2.1.20220825-0947, bash language server 3.1.0, SCxxx code is there

_SC2162: read without -r will mangle backslashes_
**echo "$*" | while IFS= read line; do**

**Comment by amurashkin17** [comment] 2023-06-04 20:54
There is also related BLS issue [#752 Feat - Show shellcheck error codes](752).

**Comment by skovhus** [comment] 2023-07-15 20:14
Duplicate of [#752 Feat - Show shellcheck error codes](https://github.com/bash-lsp/bash-language-server/issues/752).

**Closed by skovhus** 2023-07-15 20:14 UTC
