### ISSUE TITLE
rename & refactor

### ISSUE THREAD

**Issue by Freed-Wu** [bash-lsp/bash-language-server#1070] opened 2023-12-27 02:51 UTC
### What is the problem this feature will solve?

Some language servers like clangd (for C/C++), pyright (for python), tsserver(for javascript) and vim-language-server (for vim script) support rename and refactor.

## Rename

![a](https://github.com/microsoft/TypeScript/assets/32936898/ca84e08b-ec27-4dcd-b1b6-7a9d221aefb2)

## Refactor

![a](https://github.com/microsoft/TypeScript/assets/32936898/2ad19f16-9c6f-40e2-bd44-749abf135405)

### What is the feature you are proposing to solve the problem?

Search AST of tree-sitter and find all nodes which type is variable and name is same, rename them to a new variable name.

**Comment by skovhus** [comment] 2023-12-27 12:21
Duplicate of https://github.com/bash-lsp/bash-language-server/issues/161, implemented in https://github.com/bash-lsp/bash-language-server/pull/915

**Closed by skovhus** 2023-12-27 12:21 UTC
Labels: enhancement
