### ISSUE TITLE
Go To Definition does not work (Bash IDE in VS Code)

### ISSUE THREAD

**Issue by timoteicampian** [bash-lsp/bash-language-server#646] opened 2022-12-31 04:05 UTC
Go To Definition does not work starting with version 1.19.0

**Comment by skovhus** [comment] 2023-01-02 06:23
Please include an example script. Unfortunately I can’t reproduce this error.

**Comment by timoteicampian** [comment] 2023-01-02 07:33
I am using it in Visual Studio Code: Right Click > "Go to Definition" or CMD + Click
Unfortunately, VSC updates the **Bash IDE** extension to the latest version after every restart. So I have to downgrade it again to 1.18.0.

**Comment by skovhus** [comment] 2023-01-02 08:01
A code example would still be great to know if this is an issue across files or jump to definition in a single file. 

Note that we recently https://github.com/bash-lsp/bash-language-server/blob/main/vscode-client/CHANGELOG.md#1210 started using source statements to narrow down the completions. If this is an issue across multiple files, then that could be the culprit.

**Comment by timoteicampian** [comment] 2023-01-02 08:33
it does not work even inside a single file

below a sample of code to check/test

`#!/usr/bin/env bash
VAR1=a
VAR2=b

func1() {
    echo $VAR1
}
func2() {
    echo $VAR2
}
main() {
    func1
    func2
}`

**Comment by skovhus** [comment] 2023-01-02 10:24
Thanks for the example here. I couldn't reproduce any issues with that example using the latest extension. So I'm curious what is going on. Can I get you to upgrade to the latest version and paste the output from the extension? You can find the log output when opening a bash file and click "View -> Output -> Bash IDE". Try clicking jump to definition and paste the entire log output here.

Thanks 🙏

**Comment by timoteicampian** [comment] 2023-01-02 14:06
sure...sorry for the late answer...many thx for your effort

**Comment by timoteicampian** [comment] 2023-01-02 14:09
onDefinition 77:7 word="config_openssh"
onHover 77:6 word="config_openssh"
onHover 77:5 word="config_openssh"
onDefinition 77:15 word=null
onHover 77:11 word="config_openssh"

**Comment by timoteicampian** [comment] 2023-01-02 14:11
onDocumentHighlight 79:7 word="config_avahi"
onDefinition 79:13 word=null
onHover 79:14 word="||"
onHover 79:7 word="config_avahi"
onReferences 79:13 word=null
onHover 81:18 word="get_status"

**Comment by timoteicampian** [comment] 2023-01-02 14:17
for the small text file was working
After scrolling down all the pages and reading all the functions from the single file, I find out that Go to Definition works

**Comment by timoteicampian** [comment] 2023-01-02 14:28
I started "**ShellCheck: Run Linting**" and it seems that _Go to Reference_ is working again!

**Comment by skovhus** [comment] 2023-01-02 14:59
> ShellCheck: Run Linting

Hm. That isn’t a Bash IDE feature.

**Comment by timoteicampian** [comment] 2023-01-02 15:00
does it came from Trunk maybe?

**Comment by timoteicampian** [comment] 2023-01-02 16:48
Yes, working fine after executing "ShellCheck: Run Linting" - thank you

**Comment by timoteicampian** [comment] 2023-01-05 14:46
Could you please reopen this case as "Go to Definition" only works up to 1.16.0 for projects opened locally or on a remote (ssh) server (for me and my college)
I have tried it a few times on different projects...

**Comment by skovhus** [comment] 2023-01-05 15:16
@timoteicampian could you provide a reproducible example that always fails for you? The example above consistently works. 

Does jump to definition start working after you modify the file?

**Comment by timoteicampian** [comment] 2023-01-05 16:06
Dear Kenneth
I was able to reproduce something using this two sample files
```
ls -1
func.sh
init.0
```

 **cat func.sh**
```
#!/usr/bin/env bash

VAR_A1=true
VAR_A2=true
a1() {
    :
}
a2() {
    :
}
a3() {
    :
}
a4() {
    :
}
a5() {
    :
}
a6() {
    :
}

```

**cat init.0**
```
#!/usr/bin/env bash

VAR_B1=true
b1() {
    :
}
b2() {
    :
}
b3() {
    :
}
b4() {
    :
}

main() {
    # source func.sh
    echo $VAR_A1
    echo $VAR_A2
    echo $VAR_B1
    echo $VAR_B2
    a1
    a2
    a3
    a4
    b1
    b2
    b3
    b4
    a5
    a6
}
main

```

Observation:
 - Go to definition & jump to function/variable within the same file always works
 - if the line `source func.sh` is active in the main function, the reference works also for functions/variables across files mentioned by the source line

Suggestion:
the reference should always work even if the source action is not so obvious, as we sometimes use loops to iterate multiple source...

**Comment by skovhus** [comment] 2023-01-05 18:05
> the reference should always work even if the source action is not so obvious, as we sometimes use loops to iterate multiple source files...

That means the we would suggest symbols an across the entire workspace, which if it contains more than a few bash files does give a rather cluttered and false suggestions/jump to definition. 

But the bahaviour is configurable. We default to analyze simple source statements, a feature that I wish to extend to analyze some dynamic sourcing and sourcing done inside functions. But if you prefer resolving symbols from the entire workspace you can use the `includeAllWorkspaceSymbols` configuration option. See https://github.com/bash-lsp/bash-language-server/blob/main/server/src/config.ts#L18

I would like to understand how we can make this behaviour more clear to the end user. I believe the current default is sane, but that can be debated. But if we keep the current default we could show a warning on source statements that we cannot parse (I.e. “failed to analyze sourced file, resolution of symbols can be configured using…”)

let me know how that sounds.

**Comment by skovhus** [comment] 2023-01-05 18:06
And I would like to see examples of source statements from you project. :)

**Comment by timoteicampian** [comment] 2023-01-05 20:27
`_source() { for i in $*; do [[ -r $i ]] && echo $i && source $i; done; }`

OR 

`#!/usr/bin/env bash
# Source wrapper for not loading functions double
[[ ${BASH_SOURCE[1]} =~ .*auto-source\.sh ]] && PARENT_SOURCE=${BASH_SOURCE[2]} || PARENT_SOURCE=${BASH_SOURCE[1]}
declare -A LIBRARY_A
# LIBRARY_A[$PARENT_SOURCE]="loaded"
# LIBRARY_A[${BASH_SOURCE[1]}]="loaded"

type _source &>/dev/null ||
	_source() {
		while [[ $1 ]]; do
			# declare -A LIBRARY_A
			# echo '${LIBRARY_A[$PARENT_SOURCE]}'=${LIBRARY_A[$PARENT_SOURCE]}
			grep -w "$1" <<<${LIBRARY_A[$PARENT_SOURCE]} || {
				LIBRARY_A[$PARENT_SOURCE]="${LIBRARY_A[$PARENT_SOURCE]} $1"
				source "$1"
				shift
			}
		done
	}
`

**Comment by timoteicampian** [comment] 2023-01-06 11:43
> > the reference should always work even if the source action is not so obvious, as we sometimes use loops to iterate multiple source files...
> 
> That means the we would suggest symbols an across the entire workspace, which if it contains more than a few bash files does give a rather cluttered and false suggestions/jump to definition.
> 
> But the bahaviour is configurable. We default to analyze simple source statements, a feature that I wish to extend to analyze some dynamic sourcing and sourcing done inside functions. But if you prefer resolving symbols from the entire workspace you can use the `includeAllWorkspaceSymbols` configuration option. See https://github.com/bash-lsp/bash-language-server/blob/main/server/src/config.ts#L18
> 
> I would like to understand how we can make this behaviour more clear to the end user. I believe the current default is sane, but that can be debated. But if we keep the current default we could show a warning on source statements that we cannot parse (I.e. “failed to analyze sourced file, resolution of symbols can be configured using…”)
> 
> let me know how that sounds.

setting _true_ includeAllWorkspaceSymbols: z.boolean().default(**true**) does not help for the latest version.
only switching back to 1.18.0 does help + **Disable Auto Update for all extensions**, otherwise after each vs code restart the extension get updated even "**Ignore Update**" for Shell IDE was activated.
the bash code is stored on a common linux server...

**Comment by skovhus** [comment] 2023-01-07 09:26
If I create the two files mentioned in https://github.com/bash-lsp/bash-language-server/issues/646#issuecomment-1372415033 in a new workspace and enable `includeAllWorkspaceSymbols` from the vscode settings then I do get jump to definition and jump to references. That isn't working for you using the latest version? Or do you have another example script that isn't working? Is it related to your setup of having a common linux server or can you also reproduce this locally? 🤔 

I'm also curious which exact version that started breaking. You mention 1.18.0 working, but could you try 1.20.1? The behaviour of parsing source commands was first introduced in 1.21.0.

> I would like to understand how we can make this behaviour more clear to the end user. I believe the current default is sane, but that can be debated. But if we keep the current default we could show a warning on source statements that we cannot parse (I.e. “failed to analyze sourced file, resolution of symbols can be configured using…”)

I've created https://github.com/bash-lsp/bash-language-server/issues/658 to capture this. Feel free to add additional input and ideas.

**Comment by skovhus** [comment] 2023-01-17 10:59
@timoteicampian can you provide an example where enabling `includeAllWorkspaceSymbols` wouldn't make jump to definition work again? I would really like to have a reproducible example so we can fix this issue.

**Comment by timoteicampian** [comment] 2023-01-17 12:17
Dear @skovhus

Your tool is such a blessing for us every single day - THANK YOU for your great contribution & efort ! ! !

I was able to reproduce our case. We often group our functions/code in curly brackets for a better organisation.
I hope this help.


```
ls -1
func.sh
init.0
```
cat func.sh

```
#!/usr/bin/env bash

{ # common
    VAR_A1=true
    VAR_A2=true
    a1() { :; }
    a2() { :; }
    a3() { :; }
    a4() { :; }
    a5() { :; }
    a6() { :; }
}
{     # os functions
    { # configuration
        func1() { :; }
        func2() { :; }
    }
    { # security
        func3() { :; }
        func4() { :; }
    }
}

```

cat init.0
```
#!/usr/bin/env bash

VAR_B1=true
VAR_B2=true
b1() { :; }
b2() { :; }
b3() { :; }
b4() { :; }

main() {
    # source func.sh
    echo $VAR_A1
    echo $VAR_A2
    echo $VAR_B1
    echo $VAR_B2
    a1
    a2
    a3
    a4
    b1
    b2
    b3
    b4
    a5
    a6
    func1
    func2
    func2
    func3
    func4
}
main
```

**Comment by skovhus** [comment] 2023-01-17 20:32
> Your tool is such a blessing for us every single day - THANK YOU for your great contribution & efort ! ! !

Thank you for the appreciation, that means a lot to me! 🙏

And the example here shows me what the problem is. I have a test case now and plan to fix this soon.

**Comment by skovhus** [comment] 2023-01-18 11:04
@timoteicampian A fix has now been released as bash-language-server@4.5.1 and the latest vscode extension 1.29.0. Let me know if it works for you and if you have ideas for future improvements.

**Comment by andreicaba** [comment] 2023-01-18 13:40
> @timoteicampian A fix has now been released as bash-language-server@4.5.1 and the latest vscode extension 1.29.0. Let me know if it works for you and if you have ideas for future improvements.

A feature that could benefit Bash IDE users greatly would be if the needed library source files to run a specific script would be automatically listed by Bash IDE - given a specific library folder where to choose from.

**Comment by andreicaba** [comment] 2023-01-18 14:30
> @andreicaba sounds interesting. Could you write up an issue with additional detail? E.g. would these be suggestions after a `source` command or? https://github.com/bash-lsp/bash-language-server/issues/new?assignees=&labels=enhancement&template=2-feature-request.yml

OK, I did it :)
https://github.com/bash-lsp/bash-language-server/issues/687

**Comment by timoteicampian** [comment] 2023-01-18 19:41
> > @timoteicampian A fix has now been released as bash-language-server@4.5.1 and the latest vscode extension 1.29.0. Let me know if it works for you and if you have ideas for future improvements.
> 

works perfectly now  - T H X  ! ! -

**Comment by timoteicampian** [comment] 2023-01-24 18:41
Sorry @skovhus to disappoint you, but I had to switch back to the stable (for me) version 1.18 again
on the same day I confirmed that the fix version is working, as I had no time to inform you or test the new version properly to understand why does not work for me...

**Comment by timoteicampian** [comment] 2023-01-24 19:15
I collected some errors [there](https://drive.google.com/drive/folders/12AvYf2ieTxj79UUpkgiCETsw3aOfwqA9?usp=sharing)

**Comment by skovhus** [comment] 2023-01-24 19:27
@timoteicampian could you share an example script that works in 1.18 but not in the latest version? The error logs just shows some files that fail to parse (I assume you removed the file names?) – I'm thinking they also failed to parse with version 1.18, so I'm curious to see some example code.

**Comment by timoteicampian** [comment] 2023-01-24 19:29
they are working nice with 1.18 all the time :)

**Comment by skovhus** [comment] 2023-01-24 19:30
> they are working nice with 1.18 all the time :)

That is great, but I would still like some example code to debug this. :)

**Comment by timoteicampian** [comment] 2023-01-24 19:31
sure...I have uploaded a example file please check, I'll put soon much more if you need them

**Comment by timoteicampian** [comment] 2023-01-24 19:44
I uploaded 2 script files + output of Bash IDE

**Closed** 2023-01-24 21:44 UTC
Labels: bug, priority ⭐️

**Comment by skovhus** [comment] 2023-01-24 22:07
Thanks for the additional scripts. It turns out that for files where the treesitter parser fails, we didn't gracefully handle this in the later version of bash-language-server. I believe the error handling in the latest extension (1.30.0) is now the same as 1.18 – but including all the new improvements. 

Let me know if it works for you.

**Comment by timoteicampian** [comment] 2023-01-25 01:50
same error for same the two files
updated errors [there](https://drive.google.com/drive/folders/12AvYf2ieTxj79UUpkgiCETsw3aOfwqA9?usp=sharing)

**Comment by skovhus** [comment] 2023-01-25 06:51
> same error for the same two files

Note that the error logs are expected. In older versions this was shown as diagnostics (in the editor) if you enabling highlight parsing errors. So the syntax errors in the logs are expected. 

Anything that is working in the old version that isn’t working in the new version? If so please be specific with an example like “jump to definition on line X”.

**Comment by skovhus** [comment] 2023-01-25 09:50
This is my findings:

progress_bar.sh:
- 1.18 jump to defintion and on hover works for `_fill`, `_empty`, but not for `_progress` as we do not parse `let` commands
- 1.30 same behaviour + improvement that hovering on `_fill` returns documentation "Build progressbar string lengths"

output_print.sh
- 1.18 same as 1.30, although jump to definition might not work if the variables are duplicated in the workspace
- 1.30 jump to definition, hover, and click works for everything but `jd_COUNTER_PRINT`, `random_op`, `b` and `c` due to parse problems.

So I conclude that 1.30 is an improvement to 1.18. Let me know if you find anything that works in 1.18, but not in 1.30.

**Comment by skovhus** [comment] 2023-01-25 17:28
Okay. The only thing I need in order to investigate and potentially fix the issue is concrete reproducible examples including what isn’t working in the latest version (steps to reproduce). As mentioned, then the two files here actually works better in the newest version.

**Comment by skovhus** [comment] 2023-01-26 07:46
Great! Yes the missing file extensions is the issue here — we currently do not support that use case. Thanks for finding this!

As mentioned you can fallback to the old way of including all workspace symbols by ignoring the source statements (see the configuration option in bash ide settings). By enabling this configuration flag all symbols in the workspace is used for completions. But ideally we want to improve the source parsing to support missing file extensions, as this would give better and more accurate picture of which symbols are actually defined where.

**Comment by skovhus** [comment] 2023-01-26 08:08
That specific problem of including symbols from a sourced file without a file extension also doesn't work in 1.18. We use the background analysis glob (configurable) to analyze the workspace. 

But with the latest extension we actually do support parsing sourced files in case the the `includeAllWorkspaceSymbols` configuration flag is disabled (this is the default). We should probably make analyzing sourced files work no matter how the `includeAllWorkspaceSymbols` configuration flag is set.


### Example

File: x.sh
```
#!/bin/sh
. ./extension

echo "It works when includeAllWorkspaceSymbols is false as we follow sourced commands ${XXX}"
```

File: ./extension
```
#!/bin/sh

# documentation for XXX
export XXX=1
```

**Comment by skovhus** [comment] 2023-01-26 09:10
A fix has been released in the vscode extension version 1.32, so in case `includeAllWorkspaceSymbols` we still use source commands to find additional files not covered by the background analysis based on the `globPattern`. This means that sourced files not matching `**/*@(.sh|.inc|.bash|.command)` should still be analyzed and used for completions, jump to definition, etc.

**Comment by skovhus** [comment] 2023-01-26 18:37
> Go to definition also doesn't work if a function is defined under where it's called. 

Yeah that is a limitation of the current scope aware heuristic, implemented in https://github.com/bash-lsp/bash-language-server/pull/649 … The new heuristic should overall be better, where the previous one just found all symbols no matter the scope. That meant that jump to definition would jump to the latest definition in many cases. 

That being said: I would love to improve the heuristic based on your examples and feedback! Thanks for providing these. This specific case should be easy to fix. 

> And - actually - if it ever is to be signaled, this potential problem can be signaled by shellcheck and it doesn't seem to be a real need to be signaled by "Bash IDE" too

My intention with improving the scope aware symbol resolution was never to signal problems to the end user but improve the overall experience by providing more accurate information — correct the previous sometimes confusing behaviour. See the different issues we fixed with the new heuristic: https://github.com/bash-lsp/bash-language-server/pull/649

What shellcheck does internally is actually flow tracing the scripts. I was hoping to avoid that complexity and provide something that would be “good enough” based on a few AST traversals. 

So any examples of scripts with incorrect behaviour is very welcome!

**Comment by skovhus** [comment] 2023-02-07 12:59
@andreicaba can I get you to create a new issue capturing your suggestions for improving this or the bugs that you experience? That would be a huge help.
