### ISSUE TITLE
"Can't find bash-language-server on your PATH...." on Arch Linux

### ISSUE THREAD

**Issue by Thommen** [bash-lsp/bash-language-server#150] opened 2019-09-25 10:30 UTC
I have Arch Linux (5.3.1), and I install Visual Studio Code (1.38.1). In my VS Code i have

> Can't find bash-language-server on your PATH. Please install it using "npm i -g bash-language-server".

I have

> bash-language-server -v       
> Version is 1.6.1

Where is the problem?

**Comment by MichaLueth** [comment] 2019-09-25 11:53
What's teh output of `echo $PATH`?

**Comment by Thommen** [comment] 2019-09-25 11:56
`/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`

**Comment by MichaLueth** [comment] 2019-09-25 11:56
Possible duplicate of #41

**Comment by Will-W** [comment] 2019-12-06 13:39
I have the same issue. I'm running on Fedora 30 and have bash-language-server installed via nix, but it's on the path correctly:
```
wwykeham@WPWLX1:~$ echo $PATH
/home/wwykeham/.nix-profile/bin:/home/wwykeham/.cargo/bin:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
wwykeham@WPWLX1:~$ bash-language-server -v
Version is 1.5.6
```

**Comment by skovhus** [comment] 2020-04-16 20:34
Please reopen if this is still an issue.

**Closed by skovhus** 2020-04-16 20:34 UTC
