### ISSUE TITLE
ENOENT error on broken symbolic links

### ISSUE THREAD

**Issue by Yanpas** [bash-lsp/bash-language-server#202] opened 2020-03-06 16:53 UTC
Example of an error:
> Request initialize failed with message: ENOENT: no such file or directory, open 

at handleResponse (/home/yan/.vscode/ex…rpc/lib/main.js:436)
	at processMessageQueue (/home/yan/.vscode/ex…rpc/lib/main.js:263)
	at Immediate.<anonymous> (/home/yan/.vscode/ex…rpc/lib/main.js:247)
	at processImmediate (internal/timers.js:439)

**Comment by skovhus** [comment] 2020-03-06 20:37
Thanks for reporting this. Can you provide more context? When does it happen? How do you reproduce the error?

**Comment by Yanpas** [comment] 2020-03-07 10:28
Didn't reproduce on my home arch machine, maybe working ubuntu pc has an older bash-ls. Closing for now

Steps I used to try:
```
svnadmin create xrepo
sxn co file://$(pwd)/xrepo x
svn co file://$(pwd)/xrepo x
cd x
mkdir a
svn add a
svn ci -m aaa
svn cp ^/a ^/b
svn cp ^/a ^/b -m br
svn up
touch b/x.sh
svn up
cd ..
svn co file://$(pwd)/xrepo/b xb
code -r xb
svn switch ^/a
svn switch ^/b
svn switch ^/a
```

**Comment by Yanpas** [comment] 2020-03-10 11:03
It was a broken symlink:
```
echo '#!/bin/bash'$'\n'echo a > a.sh
ln -s x.sh b.sh
```

Log:
```
[Info  - 14:01:55] BashLanguageServer initializing...
Analyzing files matching glob "**/*@(.sh|.inc|.bash|.command)" inside /home/yan/pg/abc
Glob resolved with 2 files after 0.098 seconds
Analyzing file:///home/yan/pg/abc/a.sh
Analyzing file:///home/yan/pg/abc/b.sh
[Error - 14:01:55] Server initialization failed.
  Message: Request initialize failed with message: ENOENT: no such file or directory, open '/home/yan/pg/abc/b.sh'
  Code: -32603 
```

**Comment by skovhus** [comment] 2020-04-14 18:57
@Yanpas thanks for reporting the root cause. This has been fixed now and will be part of the next extension release. :)

**Closed** 2020-04-14 18:56 UTC
Labels: bug

**Comment by Yanpas** [comment] 2020-04-14 19:07
@skovhus  Concerning `fs.readFileSync` I'd like to admit that it's better to avoid sync functions in node (especially in case of mixing sync and async code). They are easily replaceable with `util.promisify` and `Promise.all` (for loop)

**Comment by skovhus** [comment] 2020-04-14 20:16
> @skovhus Concerning fs.readFileSync I'd like to admit that it's better to avoid sync functions in node (especially in case of mixing sync and async code). They are easily replaceable with util.promisify and Promise.all (for loop)

Yeah, we have some work in optimizing this. It should speed up the start time – although it is currently fairly fast. If you are up for creating a PR, that would be awesome. :) 

Sidenote: Instead of `util.promisify` I do recommend the fs promises API: https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_promises_api

**Comment by Yanpas** [comment] 2020-04-14 21:39
Sure, here it is :smiley_cat:  https://github.com/bash-lsp/bash-language-server/pull/212

I decided to do it sequentially to keep the same behaviour and predictable memory consumption.
