### ISSUE TITLE
The "languageserver.bash" server crashed 4 times in the last 3 minutes. The server will not be restarted

### ISSUE THREAD

**Issue by isak102** [bash-lsp/bash-language-server#353] opened 2022-05-06 07:24 UTC
Opening a .sh file in neovim and waiting around 4 seconds leads to this issue. The language server crashes and doesn't work whatsoever. I have tried reinstalling node, bash-language-server and coc multiple times with no success.  

This started happening a few days ago, don't think I have changed anything. This is the output of `:CocCommand workspace.showOuptut`:
```
node:internal/deps/undici/undici:4816
            throw new TypeError("Failed to parse URL from " + input, { cause: err });
                  ^

TypeError: Failed to parse URL from /usr/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.wasm
    at new Request (node:internal/deps/undici/undici:4816:19)
    at Agent2.fetch2 (node:internal/deps/undici/undici:5544:29)
    ... 4 lines matching cause stack trace ...
    at /usr/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:144
    at Object.<anonymous> (/usr/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:170)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:377:5)
      at URL.onParseError (node:internal/url:563:9)
      at new URL (node:internal/url:643:5)
      at new Request (node:internal/deps/undici/undici:4814:25)
      at Agent2.fetch2 (node:internal/deps/undici/undici:5544:29)
      at Object.fetch (node:internal/deps/undici/undici:6372:20)
      at fetch (node:internal/bootstrap/pre_execution:199:25)
      at /usr/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:15041
      at /usr/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:15262
      at /usr/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:144 {
    input: '/usr/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}
```

**Comment by mrdotx** [comment] 2022-05-07 08:01
I have the same problem. A temporary solution for me is to downgrade nodejs from 18.1.0 to 17.9.0 on Arch Linux...

**Comment by isak102** [comment] 2022-05-07 08:11
> 

This worked for me too. Probably a bug in nodejs 18.1 then

**Comment by xiaobaiseven** [comment] 2022-05-07 18:16
I have the same problem when i upgraded nodejs-18.1.0.

**Comment by RealSaltyFish** [comment] 2022-05-07 20:46
Same here. Downgraded to 17.9.0 for now.

**Comment by isak102** [comment] 2022-05-18 17:37
@mrdotx @RealSaltyFish @xiaobaiseven Have you found any solutions? Node has gotten a new version, 18.2.0, and it still doesn't work

**Comment by Alexey104** [comment] 2022-05-18 17:41
> Node has gotten a new version, 18.2.0, and it still doesn't work

Confirm. Works with 18.0.0.

**Comment by Alexey104** [comment] 2022-05-18 17:48
I'm on 3.0.2.

**Comment by isak102** [comment] 2022-05-18 17:50
> On May 18, 2022 1:37:18 PM EDT, isak102 ***@***.***> wrote: @mrdotx @RealSaltyFish @xiaobaiseven Have you found any solutions? Node has gotten a new version, 18.2.0, and it still doesn't work
> What version of bash-ls are you on? This should already be fixed in 3.0.1.
> […](#)
> -- Best, Daniel <https://danielcapella.com>

I am on 3.0.2 and it doesn't work

**Comment by Alexey104** [comment] 2022-05-18 17:51
With `bash-ls 3.0.2` and `nodejs 18.2.0` I get `Server languageserver.bash failed to start: Error: Connection to server got closed. Server will not be restarted.` No problems with `nodejs 18.0.0`.

**Comment by mrdotx** [comment] 2022-05-18 17:57
> On May 18, 2022 1:37:18 PM EDT, isak102 ***@***.***> wrote: @mrdotx @RealSaltyFish @xiaobaiseven Have you found any solutions? Node has gotten a new version, 18.2.0, and it still doesn't work
> What version of bash-ls are you on? This should already be fixed in 3.0.1.
> […](#)
> -- Best, Daniel <https://danielcapella.com>

I'm also on 3.0.2 and it still doesn't work with 18.2.0

**Comment by skovhus** [comment] 2022-05-18 20:38
I cannot reproduce the issue, so I would love you to paste the output produced by running `bash-language-server --version` (to ensure the version you are on, and to see if that crashes) and the output produced by `bash-language-server start` (a stack trace I assume?).

**Comment by Alexey104** [comment] 2022-05-18 21:03
Sure.

```
alexey@archlinux: ~
bash-language-server --version                                                                                                 
Version is 3.0.2

alexey@archlinux: ~
node --version                                                                                                                
v18.2.0
```

`bash-language-server start` does not give any errors if executed manually in CLI, but nvim shows this at startup:
![bash-ls](https://user-images.githubusercontent.com/38672094/169154354-cb458b0c-05c4-44b6-b78b-f2cf697e5417.png)

I am not sure, maybe this is rather related to `Coc.nvim` than to `bash-ls`, but there are no problems with other language servers, only `bash-ls` fails to start.

**Comment by WhoIsSethDaniel** [comment] 2022-05-18 21:08
I also have this issue. I have the same error as reported in the first comment.
```
$ ./bash-language-server --version
Version is 3.0.2

$ node --version
v18.2.0
```

`bash-language-server start` does not produce any errors. It's only once the client contacts the server that the error occurs.

**Comment by skovhus** [comment] 2022-05-18 21:15
Thanks! I've reproduced the issue locally now by running the automated tests (`yarn test`). https://github.com/bash-lsp/bash-language-server/blob/master/server/src/parser.ts#L23 hangs on node 18... 

@maxbrunsfeld do you know of any issues using `web-tree-sitter` or  with node 18? The `Parser.Language.load` function just hangs...

**Comment by gegoune** [comment] 2022-05-18 22:22
That's what nvim gives in logs, hope it helps (`3.0.2` & `v18.1.0`):

```
[ERROR][2022-05-19 00:09:19] .../vim/lsp/rpc.lua:428    "rpc"   "bash-language-server"  "stderr"        "node:internal/deps/undici/undici:4816
            throw new TypeError(\"Failed to parse URL from \" + input, { cause: err });
                  ^

TypeError: Failed to parse URL from /Users/gegoune/.pnpm-global/5/.pnpm/web-tree-sitter@0.20.5/node_modules/web-tree-sitter/tree-sitter.wasm
    at new Request (node:internal/deps/undici/undici:4816:19)
    at Agent2.fetch2 (node:internal/deps/undici/undici:5544:29)
    ... 4 lines matching cause stack trace ...
    at new Promise (<anonymous>)
    at Function.init (/Users/gegoune/.pnpm-global/5/.pnpm/web-tree-sitter@0.20.5/node_modules/web-tree-sitter/tree-sitter.js:1:332)
    at Object.<anonymous> (/Users/gegoune/.pnpm-global/5/.pnpm/bash-language-server@3.0.2/node_modules/bash-language-server/out/parser.js:16:22)
    at Generator.next (<anonymous>) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:377:5)
      at URL.onParseError(node:internal/url:563:9)
      at new URL (node:internal/url:643:5)
      at new Request (node:internal/deps/undici/undici:4814:25)
      at Agent2.fetch2 (node:internal/deps/undici/undici:5544:29)
      at Object.fetch (node:internal/deps/undici/undici:6372:20)
      at fetch (node:internal/bootstrap/pre_execution:199:25)
      at /Users/gegoune/.pnpm-global/5/.pnpm/web-tree-sitter@0.20.5/node_modules/web-tree-sitter/tree-sitter.js:1:15192
      at /Users/gegoune/.pnpm-global/5/.pnpm/web-tree-sitter@0.20.5/node_modules/web-tree-sitter/tree-sitter.js:1:15413
      at new Promise (<anonymous>) {
    input: '/Users/gegoune/.pnpm-global/5/.pnpm/web-tree-sitter@0.20.5/node_modules/web-tree-sitter/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.1.0
"

```

**Comment by skovhus** [comment] 2022-05-22 08:00
A **temporary workaround** is to start the language server using the `--no-experimental-fetch` flag:
```bash
node --no-experimental-fetch $(which bash-language-server) --start  
```

@gegoune @WhoIsSethDaniel Can you verify if that works for you?

### Additional context
I've looked into this and the node.js support for `fetch` conflicts with some of the wasm code generated by [emscripten](https://github.com/emscripten-core/emscripten/blob/29999a7115cfdb3e8c6cc9dca89c87af436f03c3/src/source_map_support.js#L113) – a [downstream fix is here](https://github.com/emscripten-core/emscripten/pull/16917) and [issue here](https://github.com/emscripten-core/emscripten/issues/16915).

I've validated this by disabling fetch using `--no-experimental-fetch` when running test:
```bash
node --no-experimental-fetch  node_modules/.bin/jest server/src/__tests__/server.test.ts
```

**Comment by skovhus** [comment] 2022-05-22 08:48
Version 3.0.3 has just been released with a workaround. Let me know if it works. :)

**Comment by RealStickman** [comment] 2022-05-22 10:12
Version 3.0.3 works for me with node 18.2.0

**Comment by Alexey104** [comment] 2022-05-22 17:42
Yes, 3.0.3 works, thank you for fixing it!

**Closed** 2022-05-22 19:36 UTC
